### ISSUE TITLE
Plugin não funciona com meu tema

### ISSUE THREAD

**Issue by emanueljs1** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#116]
Olá, o seu plugin não funciona com o meu tema pago. Eles dão conflito, habilitei o debug do WP para verificar e achei o que está abaixo:

> PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function Extra_Checkout_Fields_For_Brazil_Front_End::order_formatted_billing_address(), 1 passed in /home1/espacito/public_html/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /home1/espacito/public_html/wp-content/plugins/woocommerce-extra-checkout-fields-for-brazil/includes/class-extra-checkout-fields-for-brazil-front-end.php:492
Stack trace:
#0 /home1/espacito/public_html/wp-includes/class-wp-hook.php(286): Extra_Checkout_Fields_For_Brazil_Front_End->order_formatted_billing_address(Array)
#1 /home1/espacito/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#2 /home1/espacito/public_html/wp-content/themes/moon-shop/woocommerce/order/order-details-customer.php(80): apply_filters(‘woocommerce_ord…’, Array)
#3 /home1/espacito/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(210): include(‘/home1/espacito…’)
#4 /home1/espacito/public_html/wp-content/themes/moon-shop/woocommerce/order/or in /home1/espacito/public_html/wp-content/plugins/woocommerce-extra-checkout-fields-for-brazil/includes/class-extra-checkout-fields-for-brazil-front-end.php on line 492

Eu gostaria de saber uma solução, porque você diz que o "Extra Checkout Fields for Brazil" é necessário para o PagSeguro, e eu necessito do PagSeguro para vender. 
Gostaria de ter uma versão "paga" deste plugin, onde tivesse um suporte bom.
Por favor me dá uma luz, porque estou na fase final deste projeto e as telas do fim do checkout e a visualização de pedidos pelo painel do cliente não funcionam, aparecem em branco devido a este erro. Eu vendo muitos produtos no final do ano, e sem site fica inviável.

Abraços.

**Comment by tiago-sartor** [comment]
@emanueljs1 É virtualmente impossível criar integrações para todos os temas e plugins disponíveis no repositório do WordPress. O plugin prioriza a compatibilidade com o WooCommerce e, consequentemente, com os temas e plugins que sigam os padrões do WooCommerce.
