### ISSUE TITLE
Checkout tela em branco

### ISSUE THREAD

**Issue by edsonpreis** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#141]
Atualizei o Woocommerce para 3.6.3 após pagamento o checkout fica com uma tela em branco.

Woocommerce 3.6.3
PHP: 7.3
DB: MariaDB 10.3 
Tema: MoonSix
Meios de pagamento: PagSeguro e Paypal

####LOG

2019-06-07T01:03:25+00:00 CRITICAL Uncaught ArgumentCountError: Too few arguments to function Extra_Checkout_Fields_For_Brazil_Front_End::order_formatted_billing_address(), 1 passed in /home/public_html/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /home/public_html/wp-content/plugins/woocommerce-extra-checkout-fields-for-brazil/includes/class-extra-checkout-fields-for-brazil-front-end.php:512
Stack trace:
#0 /home/public_html/wp-includes/class-wp-hook.php(286): Extra_Checkout_Fields_For_Brazil_Front_End->order_formatted_billing_address(Array)
#1 /home/public_html/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)
#2 /home/public_html/wp-content/themes/moon-shop/woocommerce/order/order-details-customer.php(80): apply_filters('woocommerce_ord...', Array)
#3 /home/public_html/wp-content/plugins/wo, em /home/public_html/wp-content/plugins/woocommerce-extra-checkout-fields-for-brazil/includes/class-extra-checkout-fields-for-brazil-front-end.php, na linha 512

###FIMLOG

Alguém com o mesmo problema ou com alguma sugestão para o caso?

Obrigado.

**Comment by tiago-sartor** [comment]
> /home/public_html/wp-content/themes/moon-shop/woocommerce/order/order-details-customer.php(80): apply_filters('woocommerce_ord...', Array)

@edsonpreis O log dá a entender que o seu tema está passando apenas 1 argumento para o hook ao invés de 2, causando um erro fatal do PHP.
